[program:challenge_api]
directory=/app/challenge_api/src
command=/usr/bin/python3 -m uvicorn app:app --host 0.0.0.0 --port 80
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:terminal_session]
directory=/app/terminal_session
command=/usr/bin/node /app/terminal_session/app.js /workspace
environment=PORT="3000"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
